name = "OscillatorOptimization"
uuid = "181038f1-4587-421a-8eaa-d494cb0e7a81"
authors = ["Claude Assistant"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
